name: Build

on:
  push:
    paths:
    - .github/workflows/build.yml
    - OpenVR.sln
    - OpenVR/**
    - OpenVR.Tasks/**
    branches:
    - '**'
    tags:
    - '**'

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up Beat Saber
      uses: nicoco007/setup-beat-saber@main
      with:
        access-token: ${{ secrets.BEAT_SABER_BINDINGS_TOKEN }}
        manifest: ${{ github.workspace }}\OpenVR\OpenVR.manifest

    - name: Build Release
      id: build-release
      run: dotnet build ${{ github.workspace }}\OpenVR\OpenVR.csproj -c Release

    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.build-release.outputs.artifact-name }}
        path: ${{ steps.build-release.outputs.artifact-path }}
